import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    mainVideoContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    partnerVideo: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#333',
    },
    partnerAvatar: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#4CAF50',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    partnerName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    myVideoContainer: {
        position: 'absolute',
        bottom: 120,
        right: 20,
        width: 120,
        height: 160,
    },
    myVideo: {
        flex: 1,
        backgroundColor: '#666',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    myAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#4CAF50',
        justifyContent: 'center',
        alignItems: 'center',
    },
    compatibilityCard: {
        position: 'absolute',
        top: 20,
        right: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        borderRadius: 12,
        padding: 15,
        minWidth: 120,
    },
    compatibilityHeader: {
        alignItems: 'center',
        marginBottom: 8,
    },
    compatibilityTitle: {
        fontSize: 12,
        color: '#4CAF50',
        fontWeight: '500',
        textAlign: 'center',
    },
    compatibilityScore: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FF6B6B',
        textAlign: 'center',
        marginBottom: 4,
    },
    compatibilityFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    compatibilityRating: {
        fontSize: 12,
        color: '#fff',
        marginRight: 4,
    },
    partnerProfileButton: {
        position: 'absolute',
        top: 20,
        left: 20,
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    partnerProfileAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#4CAF50',
        justifyContent: 'center',
        alignItems: 'center',
    },
    controlsBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 20,
        paddingBottom: 30, // 하단 안전 영역 고려
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        gap: 20,
    },
    controlButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    controlButtonOff: {
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
    endCallButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#E53935',
        justifyContent: 'center',
        alignItems: 'center',
    },
    reportButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        justifyContent: 'center',
        alignItems: 'center',
    },

    // 프로필 모달 스타일
    profileModalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    profileModal: {
        backgroundColor: '#fff',
        borderRadius: 20,
        maxHeight: '80%',
        width: '90%',
        maxWidth: 400,
        paddingTop: 20,
    },
    profileModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    profileModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
    },
    closeButton: {
        padding: 5,
    },
    profileModalContent: {
        padding: 20,
        alignItems: 'center',
    },
    profileAvatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#4CAF50',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 15,
    },
    profileName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 5,
    },
    profileLocation: {
        fontSize: 16,
        color: '#666',
        marginBottom: 15,
    },
    profileStats: {
        flexDirection: 'row',
        marginBottom: 20,
    },
    statItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 15,
    },
    statText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginLeft: 5,
    },
    aboutSection: {
        width: '100%',
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 10,
    },
    aboutText: {
        fontSize: 14,
        color: '#666',
        lineHeight: 20,
    },
    keywordsSection: {
        width: '100%',
        marginBottom: 20,
    },
    keywordsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    keywordTag: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#4CAF50',
        borderRadius: 15,
        paddingHorizontal: 12,
        paddingVertical: 6,
        marginRight: 8,
        marginBottom: 8,
    },
    keywordText: {
        fontSize: 14,
        color: '#4CAF50',
        fontWeight: '500',
    },
    
    // 액션 버튼 컨테이너
    actionButtonsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        justifyContent: 'space-between',
    },
    heartButton: {
        backgroundColor: '#f8f9fa',
        borderRadius: 25,
        paddingHorizontal: 20,
        paddingVertical: 12,
        flex: 1,
        marginRight: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addFriendButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        borderRadius: 25,
        paddingHorizontal: 20,
        paddingVertical: 12,
        flex: 2,
        justifyContent: 'center',
    },
    addFriendText: {
        fontSize: 16,
        color: '#4CAF50',
        fontWeight: '500',
        marginLeft: 8,
    },
    chatButton: {
        backgroundColor: '#f8f9fa',
        borderRadius: 25,
        paddingHorizontal: 20,
        paddingVertical: 12,
        flex: 1,
        marginRight: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    removeFriendButton: {
        backgroundColor: '#f8f9fa',
        borderRadius: 25,
        paddingHorizontal: 20,
        paddingVertical: 12,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
});

export default styles;
